// Report writer: turns the raw findings + flow results into a triage-ready
// markdown report, written to .kiro/ship-v2/26-live-verification-report.md and
// mirrored into the run dir. No em or en dashes anywhere.

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const SEV_ORDER = { high: 0, medium: 1, low: 2 }

function detailSig(f) {
  const d = f.detail || {}
  switch (f.type) {
    case 'failed_request':
    case 'request_failed': return `${d.status || d.failure || ''} ${d.url || ''}`
    case 'console_error': return (d.text || '').slice(0, 200)
    case 'page_error': return (d.message || '').slice(0, 200)
    case 'csp_violation': return `${d.violatedDirective || ''} ${d.blockedURI || ''}`
    case 'broken_image': return d.src || ''
    case 'h_overflow': return `overflow ${d.overflowPx}px`
    case 'navigation_error':
    case 'flow_assert': return (d.message || '').slice(0, 200)
    default: return JSON.stringify(d).slice(0, 200)
  }
}

function cell(f) {
  const where = f.page || f.step || '?'
  // h_overflow is viewport-dependent, keep viewport in the dedup identity
  const vpKey = f.type === 'h_overflow' ? `:${f.viewport}` : ''
  return { key: `${f.type}|${where}${vpKey}|${detailSig(f)}`, where }
}

function groupFindings(findings) {
  const map = new Map()
  for (const f of findings) {
    const { key, where } = cell(f)
    if (!map.has(key)) {
      map.set(key, { type: f.type, severity: f.severity, where, sig: detailSig(f), detail: f.detail, occurrences: [], shots: new Set() })
    }
    const g = map.get(key)
    g.occurrences.push(`${f.viewport || '-'}/${f.theme || '-'}/${f.auth || '-'}`)
    if (f.shot) g.shots.add(f.shot)
    // keep highest severity seen
    if (SEV_ORDER[f.severity] < SEV_ORDER[g.severity]) g.severity = f.severity
  }
  return [...map.values()].sort((a, b) => SEV_ORDER[a.severity] - SEV_ORDER[b.severity] || a.type.localeCompare(b.type))
}

function fmtDetail(g) {
  const d = g.detail || {}
  const bits = []
  if (d.url) bits.push(`\`${d.url}\``)
  if (d.status) bits.push(`status ${d.status}`)
  if (d.failure) bits.push(d.failure)
  if (d.text) bits.push(d.text.slice(0, 300))
  if (d.message) bits.push(d.message.slice(0, 300))
  if (d.violatedDirective) bits.push(`directive \`${d.violatedDirective}\`, blocked \`${d.blockedURI}\``)
  if (d.src) bits.push(`img \`${d.src}\``)
  if (d.overflowPx) {
    bits.push(`${d.overflowPx}px past viewport`)
    if (d.offenders?.length) bits.push('offenders: ' + d.offenders.map((o) => `${o.tag}.${o.cls || ''}(r${o.right}/w${o.width})`).join(', '))
  }
  return bits.join(' | ')
}

function uniq(arr) { return [...new Set(arr)] }

export function writeReport({ manifest, findings, pageRecords, flowResults, RUN_DIR, REPO_ROOT }) {
  const grouped = groupFindings(findings)
  const high = grouped.filter((g) => g.severity === 'high')
  const medium = grouped.filter((g) => g.severity === 'medium')
  const low = grouped.filter((g) => g.severity === 'low')

  const verdict = high.length === 0
    ? 'PASS (no high-severity findings)'
    : `REVIEW (${high.length} high-severity finding group(s))`

  const L = []
  L.push('# 26 - Live verification report')
  L.push('')
  L.push(`**Target:** ${manifest.baseUrl}  `)
  L.push(`**Run:** ${manifest.stamp} (${manifest.durationS}s)  `)
  L.push(`**Auth scope:** ${manifest.authMode}  `)
  L.push(`**Verdict:** ${verdict}`)
  L.push('')
  L.push('> Generated by `tests/live-verification/run.mjs`. Screenshots (full-page, top to bottom)')
  L.push('> are the visual baseline for future-deploy diffing. Re-run any time with a new `BASE_URL`.')
  L.push('')

  // counts
  const byType = {}
  for (const g of grouped) byType[g.type] = (byType[g.type] || 0) + 1
  L.push('## Summary')
  L.push('')
  L.push(`- Screenshots captured: **${manifest.screenshots}** across ${manifest.pageCount} routes x viewport x theme x auth`)
  L.push(`- Finding groups: **${grouped.length}** (high ${high.length} / medium ${medium.length} / low ${low.length}); raw events ${findings.length}`)
  L.push(`- Flows run: **${flowResults.length}** (${flowResults.filter((f) => f.ok).length} ok, ${flowResults.filter((f) => !f.ok).length} with issues)`)
  if (Object.keys(byType).length) {
    L.push('')
    L.push('| Type | Groups |')
    L.push('|---|---|')
    for (const [k, v] of Object.entries(byType).sort((a, b) => b[1] - a[1])) L.push(`| ${k} | ${v} |`)
  }
  if (manifest.warnings?.length) {
    L.push('')
    L.push('**Run warnings:**')
    for (const w of manifest.warnings) L.push(`- ${w}`)
  }
  L.push('')

  const section = (title, groups) => {
    L.push(`## ${title} (${groups.length})`)
    L.push('')
    if (!groups.length) { L.push('_None._'); L.push(''); return }
    for (const g of groups) {
      const cells = uniq(g.occurrences)
      L.push(`### \`${g.type}\` - ${g.where}`)
      L.push('')
      L.push(`- **Detail:** ${fmtDetail(g) || g.sig}`)
      L.push(`- **Seen in:** ${cells.length} cell(s): ${cells.join(', ')}`)
      if (g.shots.size) L.push(`- **Screenshot:** \`${[...g.shots][0]}\``)
      L.push('')
    }
  }
  section('High-severity findings', high)
  section('Medium-severity findings', medium)

  // low: compact
  L.push(`## Low-severity findings (${low.length})`)
  L.push('')
  if (!low.length) { L.push('_None._') } else {
    L.push('Mostly third-party (analytics / Turnstile / Ko-fi) network or console noise; listed for completeness.')
    L.push('')
    L.push('| Type | Where | Detail | Cells |')
    L.push('|---|---|---|---|')
    for (const g of low) L.push(`| ${g.type} | ${g.where} | ${(fmtDetail(g) || g.sig).slice(0, 100).replace(/\|/g, '/')} | ${uniq(g.occurrences).length} |`)
  }
  L.push('')

  // flows
  L.push('## Flows')
  L.push('')
  L.push('| Flow | Result | Steps | Notes |')
  L.push('|---|---|---|---|')
  for (const f of flowResults) {
    const res = f.ok ? 'ok' : 'ISSUE'
    const notes = f.error ? f.error.slice(0, 80) : (f.total ? `${f.total} questions` : '')
    L.push(`| ${f.name} | ${res} | ${f.steps.join(' > ') || '-'} | ${notes.replace(/\|/g, '/')} |`)
  }
  L.push('')

  // redirects + non-200
  const redirects = pageRecords.filter((p) => p.redirected)
  const non200 = pageRecords.filter((p) => p.status && p.status >= 400)
  L.push('## Navigation notes')
  L.push('')
  if (non200.length) {
    L.push('**Non-2xx page loads:**')
    for (const p of non200) L.push(`- ${p.page} (${p.viewport}/${p.theme}/${p.auth}) -> ${p.status}`)
    L.push('')
  }
  if (redirects.length) {
    L.push('**Redirects (final URL differs from requested):**')
    for (const p of uniqBy(redirects, (p) => `${p.page}->${p.finalUrl}|${p.auth}`)) {
      L.push(`- ${p.page} (${p.auth}) -> ${p.finalUrl}`)
    }
    L.push('')
  }
  if (!non200.length && !redirects.length) { L.push('_All pages loaded 2xx with no unexpected redirects._'); L.push('') }

  // page index
  L.push('## Page capture index')
  L.push('')
  L.push('| Route | Indexable | Auth states captured | Statuses |')
  L.push('|---|---|---|---|')
  const byRoute = new Map()
  for (const p of pageRecords) {
    if (!byRoute.has(p.page)) byRoute.set(p.page, { auth: new Set(), status: new Set(), indexable: undefined })
    const r = byRoute.get(p.page)
    r.auth.add(p.auth)
    if (p.status) r.status.add(p.status)
  }
  for (const [route, r] of byRoute) {
    L.push(`| ${route} | ${route.startsWith('/aws') && !route.includes('practice') && !route.includes('exam') ? 'yes' : (['/', '/about', '/blog', '/privacy', '/terms', '/contribute'].some((x) => route === x || route.startsWith('/blog')) ? 'yes' : 'no')} | ${[...r.auth].join(', ')} | ${[...r.status].join(', ') || '-'} |`)
  }
  L.push('')

  L.push('## Artifacts')
  L.push('')
  L.push(`- Screenshots: \`${RUN_DIR.replace(REPO_ROOT + '/', '')}/screenshots/\``)
  L.push(`- Raw findings: \`${RUN_DIR.replace(REPO_ROOT + '/', '')}/findings.json\``)
  L.push(`- Manifest: \`${RUN_DIR.replace(REPO_ROOT + '/', '')}/manifest.json\``)
  L.push('')
  L.push('## Triage / next actions')
  L.push('')
  if (high.length) {
    L.push('Each high-severity group above is a candidate bug. Route real defects into the owning')
    L.push('`.kiro/ship-v2` task doc (02 data, 05 security/CSP, 07 perf, 01 readability, 25 logged-in UX);')
    L.push('mark known/expected ones inline.')
  } else {
    L.push('No high-severity findings. Spot-check the medium/low groups, then accept this run as the')
    L.push('visual baseline. Re-run on the next deploy and diff screenshots.')
  }
  L.push('')

  const md = L.join('\n')
  // Always write the per-run report (unique path, no cross-chat collision).
  const perRun = resolve(RUN_DIR, 'report.md')
  writeFileSync(perRun, md)
  // The shared canonical report (.kiro/ship-v2/26-live-verification-report.md)
  // is a single file: multiple concurrent runs would clobber it. Only write it
  // when explicitly opted in (LV_WRITE_CANONICAL=1) or to a custom LV_REPORT_PATH.
  const canonical = process.env.LV_REPORT_PATH
    || (process.env.LV_WRITE_CANONICAL === '1' ? resolve(REPO_ROOT, '.kiro/ship-v2/26-live-verification-report.md') : null)
  if (canonical) writeFileSync(canonical, md)
  return { perRun, canonical }
}

function uniqBy(arr, keyFn) {
  const seen = new Set(); const out = []
  for (const x of arr) { const k = keyFn(x); if (!seen.has(k)) { seen.add(k); out.push(x) } }
  return out
}
